# fly.toml file generated for quizardapi on 2022-11-06T22:33:48-05:00

app = "quizardapi"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"
  MONGODB_URI = "mongodb+srv://harrisimon:Duct7apeWallet@movielogger.rvys3ds.mongodb.net/?retryWrites=true&w=majority"
  CLIENT_ORIGIN = "https://quizard-by-tuneheads.netlify.app/"


[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
